### ISSUE TITLE
[BE/Task] MongoDB Schema/API 작성하기

### ISSUE THREAD

**Issue by Ensil-dev** [codestates/JoopJoop#22]
### ISSUE
- Group: `server`
- Type: `SR`
- Detail: MongoDB 양식에 맞게끔 JoopJoop API 작성하기

### TODO
1. [x]  MongoDB Schema/API 작성법 학습
2. [x] JoopJoop MongoDB Schema 작성
3. [x] JoopJoop MongoDB API 작성
