### ISSUE TITLE
[BE/Task] 모임 조회

### ISSUE THREAD

**Issue by L9628** [codestates/JoopJoop#235]
### ISSUE
- Group:  `server`
- Type: `feature`
- Detail: client에서 모임 조회 요청시 DB에있는 모임 조회하기

### TODO
1. [x] client에서 모임 조회 요청시 DB에있는 모임 조회하기
 - [x] 전체 모임 조회
 - [x] 특정 모임 조회
