### ISSUE TITLE
[BE/Task] 게시글 조회

### ISSUE THREAD

**Issue by L9628** [codestates/JoopJoop#239]
### ISSUE
- Group:  `server`
- Type: `feature`
- Detail: client에서 게시글 조회 요청시 mongodb에 게시글 조회

### TODO
1. [x] client에서 게시글 조회 요청시 mongodb에 게시글 조회
 - [x] 전체 게시글 조회
 - [x] 특정 유저가 작성한 게시글 조회
