### ISSUE TITLE
[FE/Task] Nav bar

### ISSUE THREAD

**Issue by meanjeful** [codestates/JoopJoop#24]
### ISSUE
- Group:  `client`
- Type: `feature`
- Detail: Nav bar 만들기

### TODO
1. [x] 로고 만들기
2. [x] 홈 버튼 만들기
3. [x] 일정 버튼 만들기
4. [x] 채팅 버튼 만들기
5. [x] 커뮤니티 버튼 만들기
6. [x] 알림 드랍다운 만들기
7. [x] 더보기 드랍다운 만들기
