### ISSUE TITLE
[BE/Task] 게시글 댓글 조회

### ISSUE THREAD

**Issue by L9628** [codestates/JoopJoop#244]
### ISSUE
- Group:  `server`
- Type: `feature`
- Detail: client에서 게시글 댓글 조회 요청시 DB에있는 게시글 댓글 조회하기

### TODO
1. [x] client에서 게시글 댓글 조회 요청시 DB에있는 게시글 댓글 조회하기
 - [x] 특정 유저의 전체 댓글 조회
 - [x] 특정 유저의 특정 댓글 조회
