### ISSUE TITLE
[FE/Task] 재사용 컴포넌트2

### ISSUE THREAD

**Issue by woobaeh** [codestates/JoopJoop#30]
### ISSUE
- Group:  `client`
- Type: `feature`
- Detail: 재사용 컴포넌트2

### TODO
1. [x] 로딩 UI
2. [x] 지도 미리보기
3. [x] 지역 선택 인풋
4. [x] 날짜 선택 인풋
5. [x] 시간 선택 인풋
6. [x] 내 위치 보기 버튼
