### ISSUE TITLE
[FE/Task] 모임 조회 모달

### ISSUE THREAD

**Issue by meanjeful** [codestates/JoopJoop#33]
### ISSUE
- Group:  `client`
- Type: `feature`
- Detail: 모임 조회 모달

### TODO
1. [ ] 지도 표시(핀)
2. [ ] 사진, 닉네임 표시
3. [ ] 댓글 기능
4. [ ] 모임 참가 버튼
5. [ ] 모임 참가 취소 버튼
6. [ ] 날짜, 시간, 참여자 목록 리스트
7. [ ] 채팅방 링크 버튼
